version: 1.0.0_b{build}-{branch}

os: Visual Studio 2015

environment:
  TERM: dumb
  PYTHON_BIN: python
  CRAM_SHELL: "C:\\msys64\\usr\\bin\\sh.exe"
  matrix:
  - COMPILER: msvc
    GENERATOR: "Visual Studio 14 2015"
    CFLAGS: /MP
    CXXFLAGS: /MP
    BUILD_FLAGS: /verbosity:m
  - COMPILER: mingw
    GENERATOR: "MSYS Makefiles"
    BUILD_FLAGS: -j2

platform:
  - x86
  - x64

configuration:
  - Debug
  - RelWithDebInfo

init:
  - set PATH=C:\Python35;C:\Python35\Scripts;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%APPVEYOR_BUILD_FOLDER%\build;%APPVEYOR_BUILD_FOLDER%\build\Debug;%PATH%
  - set MSYSTEM=MINGW64
  - pip install cram==0.7

  # Remove Xamarin msbuild warnings
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

install:
  - ps: $env:RELEASE_NAME = $env:APPVEYOR_REPO_BRANCH -replace "/", "-"
  # Hack to make git think it is on the tip of the repo branch
  - 'git checkout -B %APPVEYOR_REPO_BRANCH%'

  # Patch buggy cram
  - sh -c "patch /c/Python35/lib/site-packages/cram/_test.py .cmake/cram-env.patch"

  - mkdir build && cd build
  - >
      cmake
      -Wno-dev
      -DCMAKE_INSTALL_PREFIX=boxfort-%RELEASE_NAME%
      -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
      %CMAKE_OPTS%
      -G "%GENERATOR%"
      ..

build_script:
  - cmake --build . -- %BUILD_FLAGS%

test_script:
  - ctest -j2 --output-on-failure --timeout=10
